### PR TITLE
[WIP] Explicitly add the data

### PR DESCRIPTION
**Pull request by betatim**
This is a follow up to #33 to fix the missing data.

Are there other things we should copy over?

This PR targets the `binder` branch (learning from last time). How do you keep `master` and `binder` in sync? Maybe it should target `master` and you merge it over again?

### CODE REVIEW

**Comment by betatim** [comment]
the new environment can be test driven on https://mybinder.org/v2/gh/betatim/MCL-DSCI-011-programming-in-python/patch-1 Lets use that to check if there are other things that need copying and that the data ends up in the right place.

**Comment by hfboyce** [comment]
First off, Thank you for helping! 

>Are there other things we should copy over?

I think the data is the only thing that is explicitly needed in binder. 


> This PR targets the binder branch (learning from last time). How do you keep master and binder in sync? Maybe it should target master and you merge it over again?

I'm still learning exactly how all this works but I had it targeting master at some point but I followed Ines' repo which uses a binder branch and  I usually merge the two branch when I add new data.

I'm going to merge and see how this works!

**Comment by hfboyce** [comment]
This fixed it!!! It works!

**Comment by betatim** [comment]
Sounds good. I think 10s is probably/realistically as fast as it will get. Maybe 8s but that is about 10s.

The important thing to keep in mind is that there is the time to build the initial image (probably minutes?) and the time to launch it if there was already a built image. People working on the repo probably experience the former far more often than the latter (content changes all the time while creating a course). However users probably only ever see the latter (content changes slowly during a course once it is live)

**Comment by betatim** [comment]
10s is veeeerryyy long when all you have is a little message "launching binder...". At least it is long enough to make me check if it has broken somehow or why it isn't moving forwards. Then when I think about all the stuff that happens during a launch I think "10s is pretty quick".

If someone has a smart idea how to distract people during those 10/15/30s so that it feels like time is passing faster that would be great. We've discussed showing people a short cat video, a picture from unsplash, useful facts, etc but nothing has really gotten people excited. Maybe y'all have an idea.

**Comment by hfboyce** [comment]
My colleagued just ran it and she's not run it before and said all it was ~10-15 seconds which I think is phenomenal considering I timed it before the changes and it clocked in a 1min 10 seconds. Keep in mind it has also taken between 3-5 minutes before. 

The first thing that came to mind for the distraction was something similar to how chrome has the dinosaur game when your internet is out. I'm not sure if this is stretching the limits of what is possible but that would keep people engaged. (my old work would keep a high score tally when our internet was down across the office)

**Pull request merged**
